# Generated by Django 6.0 on 2025-12-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_content', models.TextField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('labeling', 'Labeling'), ('completed', 'Completed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('chat_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.chatdocument')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chat_document', 'order')},
            },
        ),
    ]
