# Generated by Django 5.1.4 on 2025-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('labeling', 'Labeling'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
